name: CI/CD Pipeline

# Trigger the pipeline on specific events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define jobs
jobs:
  build:
    # Define the environment where the steps run
    runs-on: ubuntu-latest

    # Steps to execute
    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests (Uncomment this if you want to run tests before building)
      # - name: Run Tests
      #   run: npm test

      # Build the application
      - name: Build Application
        run: npm run build

  deploy:
    # This job runs only after 'build' succeeds
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Koyeb deployment
      - name: Deploy to Koyeb
        env:
          KOYEB_API_KEY: ${{ secrets.KOYEB_API_KEY }}  # Use the secret API key for authentication
        run: |
          curl -X POST https://api.koyeb.com/v1/apps/meaningful-gayal/deploy \
          -H "Authorization: Bearer $KOYEB_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"branch": "main"}'
